# Generated by Django 3.0.8 on 2020-07-17 15:04

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название принтера')),
                ('api_key', models.CharField(max_length=50, verbose_name='Ключ доступа к API')),
                ('check_type', models.CharField(choices=[('0', 'kitchen'), ('1', 'client')], max_length=1, verbose_name='Тип чека')),
                ('point_id', models.IntegerField(verbose_name='Номер точки')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'kitchen'), ('1', 'client')], max_length=50, verbose_name='Тип чека')),
                ('order', jsonfield.fields.JSONField(default=dict, verbose_name='Информация о заказе')),
                ('status', models.CharField(choices=[('0', 'new'), ('1', 'rendered'), ('2', 'printed')], max_length=1, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(upload_to='', verbose_name='Ссылка на pdf')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Printer', verbose_name='ID принтера')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
