# Generated by Django 3.0.8 on 2020-07-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_check_point_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='order_id',
            field=models.IntegerField(null=True, verbose_name='Номер чека'),
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Ссылка на pdf'),
        ),
        migrations.AlterField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Printer', verbose_name='ID принтера'),
        ),
    ]
