# Generated by Django 3.0.8 on 2020-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200720_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='media/pdf', verbose_name='Ссылка на pdf'),
        ),
    ]
